#include "game.h"
#include "title.h"
#include "start.h"
//#include "L1.h"
//#include "L6.h"
//#include "L10.h"
#include "win.h"
#include "loss.h"
#include "player.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  PLAY,
  INSTRUCTIONS,
  START_LEVEL,
  WIN,
  LOSE,
  STATS
} GBAState;

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  // u32 previousButtons = BUTTONS;
  // u32 currentButtons = BUTTONS;

  // Load initial game state
  // GBAState state = START;
  // int level = 1;
  // int enemy_count = 0;
  // int fp = 0;
  // Player player;
  // player.size_x = 10;
  // player.size_y = 10;
  // player.shield = 0;
  // int speed = 0;
  // Enemy enemy[MAX_ENEMIES];
  // int flag = 0;
  // //time_t secs;
  // int dub = 0;
  drawRectDMA(0, 0, 240, 160, GRAY);
  while (1) {
    waitForVBlank();
    drawsqd(start, 50, WHITE);
  }

  // while (1) {
  //   currentButtons = BUTTONS;  // Load the current state of the buttons
  //   waitForVBlank();
  //   if (KEY_DOWN_2(BUTTON_SELECT)) {
  //     state = START;
  //   }

  //   /* TODO: */
  //   // Manipulate the state machine below as needed //
  //   // NOTE: Call waitForVBlank() before you draw

  //   switch (state) {
  //     case START:
  //       //drawCenteredString(10, 10, 50, 50, "Start", RED);
  //     //printf("Start");
  //       drawFullScreenImageDMA(Title);
  //       if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
  //         state = INSTRUCTIONS;
  //       }

  //       // state = ?
  //       break;
  //     case INSTRUCTIONS:
  //       //drawCenteredString(10, 10, 50, 50, "INS", RED);
  //     //printf("Ins");
  //       drawFullScreenImageDMA(start);
  //       if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
  //         state = START_LEVEL;
  //       }
  //       break;
  //     case START_LEVEL:
  //     //printf("Start_Level");
  //     //secs = time(NULL);
  //       if (level < 6){
  //         drawRectDMA(0,0, 240, 160, BLACK);
  //         initialize(&player, enemy, level - 1);
  //         enemy_count = level - 1;
  //         speed = 1;
  //       }
  //       else if (level < 8) {
  //         drawRectDMA(0, 0, 240, 160, BLACK);
  //         initialize(&player, enemy, level + 1);
  //         enemy_count = level + 1;
  //         speed = level - 3;
  //       }
  //       else {
  //         drawRectDMA(0, 0, 240, 160, BLACK);
  //         enemy_count = MAX_ENEMIES;
  //         initialize(&player, enemy, MAX_ENEMIES);
  //         speed = 6;
  //       }
  //       state = PLAY;
  //       break;

  //     case PLAY:
  //       //drawCenteredString(10, 10, 50, 50, "PLAY", RED);
  //     //printf("Play");
  //       if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
  //         state = START_LEVEL;
  //       } else if (isWin(&player)) {
  //         dub = 1;
  //         state = STATS;
  //       } else {
  //         if (level < 6) {
  //           coverPieces(player, enemy, enemy_count, BLACK);
  //         }
  //         else if (level < 10) {
  //           coverPieces(player, enemy, enemy_count, BLACK);
  //         }
  //         else {
  //           coverPieces(player, enemy, enemy_count, BLACK);
  //         }
  //         movePlayer(&player, KEY_DOWN_2(BUTTON_UP), KEY_DOWN_2(BUTTON_DOWN), KEY_DOWN_2(BUTTON_RIGHT), KEY_DOWN_2(BUTTON_LEFT));
  //         if (fp % 3 == 0) {
  //           for (int j = 0; j < enemy_count; j++) {
  //               if (moveEnemy(&enemy[j], speed, &player)) {
  //                 flag = 1;
  //               }
  //           }
  //         }
  //         if (flag) {
  //           state = STATS;
  //           dub = 0;
  //         } else {
  //           state = PLAY;
  //         }
  //         flag = 0;
  //         drawPieces(&player, enemy, enemy_count);
  //       }
  //       break;
  //     case WIN:
  //       drawFullScreenImageDMA(win);
  //       if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
  //         state = START_LEVEL;
  //         level++;
  //       } else if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
  //         state = START_LEVEL;
  //       } else {
  //         state = WIN;
  //       }
  //       break;
  //     case LOSE:
  //       drawFullScreenImageDMA(loss);
  //       if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
  //         state = START_LEVEL;
  //       } else {
  //         state = LOSE;
  //       }
  //       // state = ?
  //       break;
  //       case STATS:
  //         drawStatsWin(level, enemy_count);
  //         if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
  //           if (!dub) {
  //             drawFullScreenImageDMA(loss);
  //             state = LOSE;
  //           } else {
  //             drawFullScreenImageDMA(win);
  //             state = WIN;
  //           }
  //         } else {
  //           state = STATS;
  //         }
  //         break;
  //   }

  //   previousButtons = currentButtons;  // Store the current state of the buttons
  //   fp++;
  // }

  return 0;
}
